package com.bootcamp.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BcConsultation generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "bootcamp")
public class Admin implements java.io.Serializable{
	private int adminId;
	private String openId;
	private String adminName;
	private String isDelete;
	
	public Admin() {
		
	}

	public Admin(int adminId, String openId, String adminName,String isDelete) {
		this.adminId = adminId;
		this.openId = openId;
		this.adminName = adminName;
		this.isDelete = isDelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "admin_id", unique = true, nullable = false)
	public int getAdminId() {
		return adminId;
	}

	public void setAdminId(int adminId) {
		this.adminId = adminId;
	}

	@Column(name = "open_id", nullable = false, length = 200)
	public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@Column(name = "admin_name", nullable = false, length = 50)
	public String getAdminName() {
		return adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}
	
	@Column(name = "isdelete", nullable = false, length = 50)
	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}
	
	
}
