package com.bootcamp.entity;
// Generated 2017-3-14 11:04:35 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LuckyDrawPeople generated by hbm2java
 * 参与人员
 */
@Entity
@Table(name = "lucky_draw_people", catalog = "bootcamp")
public class LuckyDrawPeople implements java.io.Serializable {

	private Integer luckyDrawPeopleId;
	private String luckyDrawPeopleOpenid;//微信openId
	private String luckyDrawPeopleName;//微信昵称
	private String luckyDrawPeoplePic;//微信头像
	private String luckyDrawPeopleNum;//参与人员抽奖号码
	private int luckyDrawPeopleIsDrawn;//是否已经中奖
	private int luckDrawId;//抽奖活动id
	private Date createdTime;
	private String createdBy;
	private Date updatedTime;
	private String updatedBy;
	private int isDelete;

	public LuckyDrawPeople() {
	}

	public LuckyDrawPeople(int luckyDrawPeopleIsDrawn, int luckDrawId, Date createdTime, String createdBy,
			Date updatedTime, String updatedBy, int isDelete) {
		this.luckyDrawPeopleIsDrawn = luckyDrawPeopleIsDrawn;
		this.luckDrawId = luckDrawId;
		this.createdTime = createdTime;
		this.createdBy = createdBy;
		this.updatedTime = updatedTime;
		this.updatedBy = updatedBy;
		this.isDelete = isDelete;
	}

	public LuckyDrawPeople(String luckyDrawPeopleNum, int luckyDrawPeopleIsDrawn, int luckDrawId) {
		this.luckyDrawPeopleNum = luckyDrawPeopleNum;
		this.luckyDrawPeopleIsDrawn = luckyDrawPeopleIsDrawn;
		this.luckDrawId = luckDrawId;
	}

	public LuckyDrawPeople(String luckyDrawPeopleOpenid, String luckyDrawPeopleName, String luckyDrawPeoplePic,
						   int luckDrawId) {
		this.luckyDrawPeopleOpenid = luckyDrawPeopleOpenid;
		this.luckyDrawPeopleName = luckyDrawPeopleName;
		this.luckyDrawPeoplePic = luckyDrawPeoplePic;
		this.luckDrawId = luckDrawId;
	}

	public LuckyDrawPeople(String luckyDrawPeopleOpenid, String luckyDrawPeopleName, String luckyDrawPeoplePic,
			String luckyDrawPeopleNum, int luckyDrawPeopleIsDrawn, int luckDrawId, Date createdTime, String createdBy,
			Date updatedTime, String updatedBy, int isDelete) {
		this.luckyDrawPeopleOpenid = luckyDrawPeopleOpenid;
		this.luckyDrawPeopleName = luckyDrawPeopleName;
		this.luckyDrawPeoplePic = luckyDrawPeoplePic;
		this.luckyDrawPeopleNum = luckyDrawPeopleNum;
		this.luckyDrawPeopleIsDrawn = luckyDrawPeopleIsDrawn;
		this.luckDrawId = luckDrawId;
		this.createdTime = createdTime;
		this.createdBy = createdBy;
		this.updatedTime = updatedTime;
		this.updatedBy = updatedBy;
		this.isDelete = isDelete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "lucky_draw_people_id", unique = true, nullable = false)
	public Integer getLuckyDrawPeopleId() {
		return this.luckyDrawPeopleId;
	}

	public void setLuckyDrawPeopleId(Integer luckyDrawPeopleId) {
		this.luckyDrawPeopleId = luckyDrawPeopleId;
	}

	@Column(name = "lucky_draw_people_openid", length = 100)
	public String getLuckyDrawPeopleOpenid() {
		return this.luckyDrawPeopleOpenid;
	}

	public void setLuckyDrawPeopleOpenid(String luckyDrawPeopleOpenid) {
		this.luckyDrawPeopleOpenid = luckyDrawPeopleOpenid;
	}

	@Column(name = "lucky_draw_people_name", length = 100)
	public String getLuckyDrawPeopleName() {
		return this.luckyDrawPeopleName;
	}

	public void setLuckyDrawPeopleName(String luckyDrawPeopleName) {
		this.luckyDrawPeopleName = luckyDrawPeopleName;
	}

	@Column(name = "lucky_draw_people_pic", length = 300)
	public String getLuckyDrawPeoplePic() {
		return this.luckyDrawPeoplePic;
	}

	public void setLuckyDrawPeoplePic(String luckyDrawPeoplePic) {
		this.luckyDrawPeoplePic = luckyDrawPeoplePic;
	}

	@Column(name = "lucky_draw_people_num", length = 20)
	public String getLuckyDrawPeopleNum() {
		return this.luckyDrawPeopleNum;
	}

	public void setLuckyDrawPeopleNum(String luckyDrawPeopleNum) {
		this.luckyDrawPeopleNum = luckyDrawPeopleNum;
	}

	@Column(name = "lucky_draw_people_is_drawn", nullable = false)
	public int getLuckyDrawPeopleIsDrawn() {
		return this.luckyDrawPeopleIsDrawn;
	}

	public void setLuckyDrawPeopleIsDrawn(int luckyDrawPeopleIsDrawn) {
		this.luckyDrawPeopleIsDrawn = luckyDrawPeopleIsDrawn;
	}

	@Column(name = "luck_draw_id", nullable = false)
	public int getLuckDrawId() {
		return this.luckDrawId;
	}

	public void setLuckDrawId(int luckDrawId) {
		this.luckDrawId = luckDrawId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "created_by", nullable = false, length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", nullable = false, length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Column(name = "updated_by", nullable = false, length = 15)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "isdelete", nullable = false)
	public int getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(int isDelete) {
		this.isDelete = isDelete;
	}



}
