package com.bootcamp.entity;
// Generated 2017-3-14 11:04:35 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LuckDraw generated by hbm2java
 */
@Entity
@Table(name = "luck_draw", catalog = "bootcamp")
public class LuckDraw implements java.io.Serializable {

	private Integer luckDrawId;
	private String luckDrawTitle;//抽奖标题
	private String luckDrawTitleSize;//抽奖标题大小
	private String luckDrawTitleColor;//抽奖标题颜色
	private String luckDrawTitleFont;//抽奖标题字体
	private int luckDrawIsStart;//抽奖是否开始
	private int luckDrawRandomFrequency;//抽奖滚动间隔时间
	private String luckDrawImg;//抽奖背景
	private Integer luckDrawIsWechat;//是否是微信抽奖
	private Date createdTime;
	private String createdBy;
	private Date updatedTime;
	private String updatedBy;

	public LuckDraw() {
	}

	public LuckDraw(String luckDrawTitle, int luckDrawRandomFrequency, String luckDrawImg) {
		this.luckDrawTitle = luckDrawTitle;
		this.luckDrawRandomFrequency = luckDrawRandomFrequency;
		this.luckDrawImg = luckDrawImg;
	}

	public LuckDraw(String luckDrawTitle, int luckDrawIsStart, int luckDrawRandomFrequency, String luckDrawImg,
			Date createdTime, String createdBy, Date updatedTime, String updatedBy) {
		this.luckDrawTitle = luckDrawTitle;
		this.luckDrawIsStart = luckDrawIsStart;
		this.luckDrawRandomFrequency = luckDrawRandomFrequency;
		this.luckDrawImg = luckDrawImg;
		this.createdTime = createdTime;
		this.createdBy = createdBy;
		this.updatedTime = updatedTime;
		this.updatedBy = updatedBy;
	}

	public LuckDraw(String luckDrawTitle, int luckDrawIsStart, int luckDrawRandomFrequency, String luckDrawImg,
			Integer luckDrawIsWechat, Date createdTime, String createdBy, Date updatedTime, String updatedBy) {
		this.luckDrawTitle = luckDrawTitle;
		this.luckDrawIsStart = luckDrawIsStart;
		this.luckDrawRandomFrequency = luckDrawRandomFrequency;
		this.luckDrawImg = luckDrawImg;
		this.luckDrawIsWechat = luckDrawIsWechat;
		this.createdTime = createdTime;
		this.createdBy = createdBy;
		this.updatedTime = updatedTime;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "luck_draw_id", unique = true, nullable = false)
	public Integer getLuckDrawId() {
		return this.luckDrawId;
	}

	public void setLuckDrawId(Integer luckDrawId) {
		this.luckDrawId = luckDrawId;
	}

	@Column(name = "luck_draw_title", nullable = false, length = 50)
	public String getLuckDrawTitle() {
		return this.luckDrawTitle;
	}

	public void setLuckDrawTitle(String luckDrawTitle) {
		this.luckDrawTitle = luckDrawTitle;
	}

	@Column(name = "luck_draw__is_start", nullable = false)
	public int getLuckDrawIsStart() {
		return this.luckDrawIsStart;
	}

	public void setLuckDrawIsStart(int luckDrawIsStart) {
		this.luckDrawIsStart = luckDrawIsStart;
	}

	@Column(name = "luck_draw_random_frequency", nullable = false)
	public int getLuckDrawRandomFrequency() {
		return this.luckDrawRandomFrequency;
	}

	public void setLuckDrawRandomFrequency(int luckDrawRandomFrequency) {
		this.luckDrawRandomFrequency = luckDrawRandomFrequency;
	}

	@Column(name = "luck_draw_img", nullable = false, length = 300)
	public String getLuckDrawImg() {
		return this.luckDrawImg;
	}

	public void setLuckDrawImg(String luckDrawImg) {
		this.luckDrawImg = luckDrawImg;
	}

	@Column(name = "luck_draw_is_wechat")
	public Integer getLuckDrawIsWechat() {
		return this.luckDrawIsWechat;
	}

	public void setLuckDrawIsWechat(Integer luckDrawIsWechat) {
		this.luckDrawIsWechat = luckDrawIsWechat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "created_by", nullable = false, length = 15)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", nullable = false, length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Column(name = "updated_by", nullable = false, length = 15)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "luck_draw_title_color", nullable = false, length = 50)
	public String getLuckDrawTitleColor() {
		return luckDrawTitleColor;
	}

	public void setLuckDrawTitleColor(String luckDrawTitleColor) {
		this.luckDrawTitleColor = luckDrawTitleColor;
	}

	@Column(name = "luck_draw_title_font", length = 100)
	public String getLuckDrawTitleFont() {
		return luckDrawTitleFont;
	}

	public void setLuckDrawTitleFont(String luckDrawTitleFont) {
		this.luckDrawTitleFont = luckDrawTitleFont;
	}

	@Column(name = "luck_draw_title_size", nullable = false, length = 5)
	public String getLuckDrawTitleSize() {
		return luckDrawTitleSize;
	}

	public void setLuckDrawTitleSize(String luckDrawTitleSize) {
		this.luckDrawTitleSize = luckDrawTitleSize;
	}
}
