package com.bootcamp.entity;
// Generated 2016-9-22 15:09:05 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MatchProjectScore generated by hbm2java
 */
@Entity
@Table(name = "match_project_score", catalog = "bootcamp")
public class MatchProjectScore implements java.io.Serializable {

	private Integer SId;
	private int matchProjectId;
	private int jugesId;
	private int score;
	private Date createdTime;
	private String createdBy;
	private Date updatedTime;
	private String updatedBy;

	public MatchProjectScore() {
	}

	public MatchProjectScore(int matchProjectId, int jugesId, int score, Date createdTime, String createdBy, Date updatedTime,
			String updatedBy) {
		this.matchProjectId = matchProjectId;
		this.jugesId = jugesId;
		this.score = score;
		this.createdTime = createdTime;
		this.createdBy = createdBy;
		this.updatedTime = updatedTime;
		this.updatedBy = updatedBy;
	}
	
	public MatchProjectScore(int matchProjectId, int jugesId, int score) {
		this.matchProjectId = matchProjectId;
		this.jugesId = jugesId;
		this.score = score;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "s_id", unique = true, nullable = false)
	public Integer getSId() {
		return this.SId;
	}

	public void setSId(Integer SId) {
		this.SId = SId;
	}

	@Column(name = "p_id", nullable = false)
	public int getMatchProjectId() {
		return this.matchProjectId;
	}

	public void setMatchProjectId(int matchProjectId) {
		this.matchProjectId = matchProjectId;
	}

	@Column(name = "j_id", nullable = false)
	public int getJugesId() {
		return this.jugesId;
	}

	public void setJugesId(int jugesId) {
		this.jugesId = jugesId;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "created_by", nullable = false, length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", nullable = false, length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Column(name = "updated_by", nullable = false, length = 20)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
