package com.bootcamp.entity;
// Generated 2016-9-22 15:09:05 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScoreItemDetail generated by hbm2java
 */
@Entity
@Table(name = "score_item_detail", catalog = "bootcamp")
public class ScoreItemDetail implements java.io.Serializable {

	private Integer SId;
	private String SSName;
	private int scoreItemId;
	private int matchProjectId;
	private int jugesId;
	private int SScore;
	private Date createdTime;
	private String createdBy;
	private Date updatedTime;
	private String updatedBy;

	public ScoreItemDetail() {
	}

	public ScoreItemDetail(String SSName, int scoreItemId, int matchProjectId, int jugesId, int SScore, Date createdTime, String createdBy,
			Date updatedTime, String updatedBy) {
		this.SSName = SSName;
		this.scoreItemId = scoreItemId;
		this.matchProjectId = matchProjectId;
		this.jugesId = jugesId;
		this.SScore = SScore;
		this.createdTime = createdTime;
		this.createdBy = createdBy;
		this.updatedTime = updatedTime;
		this.updatedBy = updatedBy;
	}
	
	public ScoreItemDetail(String SSName, int scoreItemId, int matchProjectId, int jugesId, int SScore) {
		this.SSName = SSName;
		this.scoreItemId = scoreItemId;
		this.matchProjectId = matchProjectId;
		this.jugesId = jugesId;
		this.SScore = SScore;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "s_id", unique = true, nullable = false)
	public Integer getSId() {
		return this.SId;
	}

	public void setSId(Integer SId) {
		this.SId = SId;
	}

	@Column(name = "s_s_name", nullable = false, length = 100)
	public String getSSName() {
		return this.SSName;
	}

	public void setSSName(String SSName) {
		this.SSName = SSName;
	}

	@Column(name = "s_s_id", nullable = false)
	public int getScoreItemId() {
		return this.scoreItemId;
	}

	public void setScoreItemId(int scoreItemId) {
		this.scoreItemId = scoreItemId;
	}

	@Column(name = "s_m_id", nullable = false)
	public int getMatchProjectId() {
		return this.matchProjectId;
	}

	public void setMatchProjectId(int matchProjectId) {
		this.matchProjectId = matchProjectId;
	}

	@Column(name = "s_j_id", nullable = false)
	public int getJugesId() {
		return this.jugesId;
	}

	public void setJugesId(int jugesId) {
		this.jugesId = jugesId;
	}

	@Column(name = "s_score", nullable = false)
	public int getSScore() {
		return this.SScore;
	}

	public void setSScore(int SScore) {
		this.SScore = SScore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", nullable = false, length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "created_by", nullable = false, length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_time", nullable = false, length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	@Column(name = "updated_by", nullable = false, length = 20)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
