package com.bootcamp.entity;
// Generated 2017-3-14 11:04:35 by Hibernate Tools 3.5.0.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * LuckDraw generated by hbm2java
 */
@Entity
@Table(name = "vote_people", catalog = "bootcamp")
public class VotePeople implements java.io.Serializable {

	private Integer votePeopleId;
	private String votePeopleIdOpenId;
	private int matchId;


	public VotePeople() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "vote_id", unique = true, nullable = false)
	public Integer getVotePeopleId() {
		return votePeopleId;
	}

	public void setVotePeopleId(Integer votePeopleId) {
		this.votePeopleId = votePeopleId;
	}

	@Column(name = "vote_openid", nullable = false, length = 100)
	public String getVotePeopleIdOpenId() {
		return votePeopleIdOpenId;
	}

	public void setVotePeopleIdOpenId(String votePeopleIdOpenId) {
		this.votePeopleIdOpenId = votePeopleIdOpenId;
	}

	@Column(name = "match_id", nullable = false)
	public int getMatchId() {
		return matchId;
	}

	public void setMatchId(int matchId) {
		this.matchId = matchId;
	}

}
