package com.bootcamp.entity;
// Generated 2017-3-14 11:04:35 by Hibernate Tools 3.5.0.Final

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * LuckDraw generated by hbm2java
 */
@Entity
@Table(name = "vote_people", catalog = "bootcamp")
public class VotePeople implements java.io.Serializable {

	private Integer VotePeopleId;
	private String VotePeopleIdOpenId;
	private String MatchId;


	public VotePeople() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "vote_id", unique = true, nullable = false)
	public Integer getVotePeopleId() {
		return VotePeopleId;
	}

	public void setVotePeopleId(Integer votePeopleId) {
		VotePeopleId = votePeopleId;
	}

	@Column(name = "vote_openid", nullable = false, length = 100)
	public String getVotePeopleIdOpenId() {
		return VotePeopleIdOpenId;
	}

	public void setVotePeopleIdOpenId(String votePeopleIdOpenId) {
		VotePeopleIdOpenId = votePeopleIdOpenId;
	}

	@Column(name = "match_id", nullable = false)
	public String getMatchId() {
		return MatchId;
	}

	public void setMatchId(String matchId) {
		MatchId = matchId;
	}

}
