package com.bootcamp.entity;
// Generated 2017-3-14 11:04:35 by Hibernate Tools 3.5.0.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * LuckDraw generated by hbm2java
 */
@Entity
@Table(name = "vote_ticket", catalog = "bootcamp")
public class VoteTicket implements java.io.Serializable {

	private Integer VoteTicketId;
	private int matchProjectId;
	private String votePeopleIdOpenId;

	public VoteTicket() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vote_ticket_id", unique = true, nullable = false)
	public Integer getVoteTicketId() {
		return VoteTicketId;
	}

	public void setVoteTicketId(Integer voteTicketId) {
		VoteTicketId = voteTicketId;
	}

	@Column(name = "vote_matct_project_id", nullable = false, length = 100)
	public int getMatchProjectId() {
		return matchProjectId;
	}

	public void setMatchProjectId(int matchProjectId) {
		this.matchProjectId = matchProjectId;
	}

	@Column(name = "vote_openid", nullable = false, length = 300)
	public String getVotePeopleIdOpenId() {
		return votePeopleIdOpenId;
	}

	public void setVotePeopleIdOpenId(String votePeopleIdOpenId) {
		this.votePeopleIdOpenId = votePeopleIdOpenId;
	}


}
